BECH32_ADDR_ACC_PREFIX = "comdex"
BECH32_ADDR_VAL_PREFIX = "comdexvaloper"
BECH32_ADDR_CONS_PREFIX = "comdexvalcons"

BECH32_PUBKEY_ACC_PREFIX = "comdexpub"
BECH32_PUBKEY_VAL_PREFIX = "comdexvaloperpub"
BECH32_PUBKEY_CONS_PREFIX = "comdexvalconspub"

DEFAULT_DERIVATION_PATH = "m/44'/118'/0'/0/0"
DEFAULT_LEDGER_DERIVATION_PATH = "m/44'/118'/0'/0/0"
