# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: comdex/asset/v1beta1/asset.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class Asset(betterproto.Message):
    id: int = betterproto.uint64_field(1)
    name: str = betterproto.string_field(2)
    denom: str = betterproto.string_field(3)
    decimals: str = betterproto.string_field(4)
    is_on_chain: bool = betterproto.bool_field(5)
    is_oracle_price_required: bool = betterproto.bool_field(6)
    is_cdp_mintable: bool = betterproto.bool_field(7)
